name: Build & Push Docker Image to Scaleway

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}
          username: nologin
          password: ${{ secrets.SCALEWAY_API_SECRET }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/portfolio:latest

      - name: Install Scaleway CLI
        uses: scaleway/action-scw@v0
        with:
          save-config: true
          export-config: true
          version: v2.39.0
          access-key: ${{ secrets.SCALEWAY_API_KEY }}
          secret-key: ${{ secrets.SCALEWAY_API_SECRET }}
          default-project-id: ${{ secrets.SCALEWAY_PROJECT_ID }}
          default-organization-id: ${{ secrets.SCALEWAY_PROJECT_ID }}

      - name: Redeploy Service
        env:
          CONTAINER_ID: ${{ secrets.SCALEWAY_CONTAINER_ID }}
          IMAGE: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/portfolio:latest
        run: |
          scw container container update $CONTAINER_ID registry-image=$IMAGE